### ISSUE TITLE
cant run project - monk problem

### ISSUE THREAD

**Issue by Monstrik** [cwbuecheler/node-tutorial-for-frontend-devs#3] opened 2016-01-07 09:16 UTC
\node-tutorial-for-frontend-devs\node_modules\mongoskin\lib\utils.js:33
  var skinClassName = 'Skin' + NativeClass.name;
                                          ^

TypeError: Cannot read property 'name' of undefined
    at makeSkinClass (e:\TempProjects\node-tutorial-for-frontend-devs\node_modules\mongoskin\lib\utils.js:33:43)
    at Object.<anonymous> (e:\TempProjects\node-tutorial-for-frontend-devs\node_modules\mongoskin\lib\grid.js:6:35)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (e:\TempProjects\node-tutorial-for-frontend-devs\node_modules\mongoskin\lib\db.js:22:16)
    at Module._compile (module.js:398:26)

**Comment by Monstrik** [comment] 2016-01-07 09:32
really it work with
 "dependencies": {
    "body-parser": "~1.13.2",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "express": "~4.13.1",
    "jade": "~1.11.0",
    "mongodb": "1.4.x",
    "monk": "~1.0.1",
    "morgan": "~1.6.1",
    "serve-favicon": "~2.3.0"
  }

**Comment by cwbuecheler** [comment] 2016-01-07 10:47
Yes, the problem is that the Mongoskin package (which Monk depends on) hasn't been updated to work with newer versions of the MongoDB package. The best solution would be to rewrite the tutorial to use Mongoose, but I don't have time right now. I'm going to update the tutorial to use the "just stick with MongoDB 1.4" solution, soon.

**Comment by Monstrik** [comment] 2016-01-07 14:08
Thank you for your patience.

**Comment by cwbuecheler** [comment] 2016-01-07 14:34
No problem! Sorry the tutorial as currently presented doesn't quite work.

**Comment by JeffReeves** [comment] 2016-01-23 06:00
Thank you for your hard work in putting this tutorial together and maintaining it. I spent about an hour trying to figure out the bug with mongoskin and eventually gave up, but I'm sure once you switch to Mongoose things will be fine again.

**Comment by mathieudutour** [comment] 2016-11-25 01:44
This is fixed with the new version of monk: https://github.com/Automattic/monk/issues/91

**Comment by cwbuecheler** [comment] 2016-11-25 03:19
I noticed that and have already updated my tutorials. Thanks!

**Closed** 2017-02-15 14:07 UTC
